# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d41b03830e87e0347800206c236cc727f19cfade67654b2a55812e91f116de5b40069aca5ee9be1d929cba5a0bb1c2ca4ff4a822f3b0819b9d3fb6ab4690a1

test:
  secret_key_base: d66d6853bb5bb6985947af64dd4d194e500960c3786015080dd3a5d28cf3af3f7b087f46f9e77cf6b305c9eaaf7aec7364e1c822eb79b2e86f7d76e6e112992d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
